# Generated by Django 4.0.5 on 2022-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название статьи')),
                ('anons', models.CharField(max_length=200, verbose_name='Анонс статьи')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
